[project]
name = "pamc-svi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "login-canaime>=2.0.0",
    "openpyxl>=3.1.5",
    "packaging>=24.2",
    "pandas>=2.2.3",
    "requests>=2.32.3",
    "xlsxwriter>=3.2.2",
]
